name: Deploy Vite Project to CentOS

on:
  push:
    branches:
      - main  # 或者你想要触发部署的其他分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # 确保使用与你项目兼容的Node.js版本

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.XIAOMI_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        scp -r -oHostKeyAlgorithms=+ssh-dss dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/yang/release/web/sc-background
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # 重新加载Nginx
          sudo systemctl reload nginx
        EOF
