name: Deploy Vite Project to CentOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.XIAOMI_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Update SSH config
      run: |
        echo -e "Host *\n\tHostkeyAlgorithms +ssh-rsa\n\tPubkeyAcceptedKeyTypes +ssh-rsa" >> ~/.ssh/config


    - name: Deploy to server
      run: |
        scp -r dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/***/release/web/sc-background
   
    - name: Restart Nginx
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.XIAOMI_PRIVATE_KEY }}
        script: |
          whoami 
          ls -al
